import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Link from "next/link";
import RoundHeroIcon from "../components/RoundHeroIcon";
import BlogCard from "../components/BlogCard";

export default function Home() {
	const bgImg =
		"https://images.unsplash.com/photo-1579975096649-e773152b04cb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80";

	let blogPosts = [
		{
			title: "First Title",
			description:
				"First description. Praesentcondimentum diam in urna tincidunt iaculis.",
		},
		{
			title: "Second Title",
			description:
				"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut lectus tortor, ullamcorper nec rhoncus non, maximus at eros. Praesentcondimentum diam in urna tincidunt iaculis.",
		},
		{
			title: "Thirdd Title",
			description:
				"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut lectus tortor, ullamcorper nec rhoncus non, maximus at eros. Praesentcondimentum diam in urna tincidunt iaculis.",
		},
	];
	return (
		<div>
			<Head>
				<title>SOC</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='w-full'>
				{/* Hero section */}
				<div className='relative w-full flex flex-col align-middle justify-evenly mx-auto h-screen bg-cover bg-center bg-no-repeat bg-hero'>
					<div className='absolute left-0 top-0 w-full h-screen backdrop-blur-0 bg-gradient-to-tr from-[#0f3d1cc7] to-purple-700/50'></div>
					<div className='relative items-center text-center flex flex-col m-4 justify-between z-10'>
						<h1 className='text-white leading-relaxed font-extrabold text-5xl md:text-8xl'>
							SOUGHT OUT CHURCH
						</h1>
						<h3 className='text-yellow-500/90 leading-relaxed font-semibold text-lg md:text-2xl pt-4'>
							CROWN OF CHRIST'S GLORY MINISTRY INT'L
						</h3>
						{/* <p className='text-white text-lg pt-4'>
						Where we give your life a meaning
					</p> */}
					</div>

					<div className='relative flex flex-col mb-8 space-y-8 space-x-0 items-center justify-center mx-auto md:flex-row md:space-x-20 md:space-y-0'>
						<RoundHeroIcon text1={"IN"} text2={"CHRIST"} />
						<RoundHeroIcon text1={"BY"} text2={"CHRIST"} />
						<RoundHeroIcon text1={"FOR"} text2={"CHRIST"} />
					</div>
				</div>

				{/* About section */}
				<div className='h-screen max-w-screen my-10 md:my-10 mx-auto'>
					<h2 className='px-4 max-w-fit text-yellow-500 border-b-2 border-b-yellow-500/40'>
						ABOUT US
					</h2>
					<div className='md:mt-8 flex flex-col lg:flex-row justify-around lg:justify-center items-center p-4 min-h-full max-w-fit'>
						<div className='h-full flex w-full mr-8 md:mr-0 px-4 self-center place-content-center content-center'>
							<div className='rounded-2xl shadow-lg shadow-[#0f3d1c] bg-hero bg-cover h-48 w-72 -mr-8 -mt-8 md:h-72 md:w-96 md:-mr-10 md:-mt-24'></div>
							<div className='rounded-2xl shadow-lg shadow-[#0f3d1c] bg-[url("/img/particle8.gif")] bg-cover bg-yellow-500 h-48 w-56 -mt-20 mr-6 md:h-72 md:w-80 md:-mt-48'></div>
							<div className='rounded-2xl shadow-lg shadow-purple-900 bg-purple-900 h-52 w-52 -ml-52 mt-8 md:h-72 md:w-72 md:-ml-[26rem] md:-mb-72'></div>
						</div>
						<div className='px-4 md:w-3/4 lg:w-full self-center justify-self-center'>
							<p className='leading-relaxed text-lg'>
								Crown of Christ's Glory International (Sought Out Church) is a
								house for those who desire God and want their life to count.
							</p>
						</div>
					</div>
				</div>

				{/* word fellowship prayer */}
				<div className='w-full flex flex-col items-center md:flex-row justify-center mx-auto p-4 space-y-4 space-x-0 md:space-x-4 md:space-y-0'>
					<div className='relative rounded-xl h-96 w-96 shadow-lg shadow-purple-900'>
						<div className='absolute rounded-xl left-0 top-0 z-10 w-full h-full bg-[#3D0066] opacity-90 bg-blend-overlay'></div>
						<div className='relative rounded-xl bg-hero w-full h-full flex items-center text-center justify-center'>
							<h1 className='text-white text-4xl font-bold z-20'>THE WORD</h1>
						</div>
					</div>
					<div className='relative rounded-xl h-96 w-96 shadow-lg shadow-[#FDC500]'>
						<div className='absolute rounded-xl left-0 top-0 z-10 w-full h-full bg-[#fdc600ef] opacity-90 bg-blend-overlay'></div>
						<div className='relative rounded-xl bg-hero w-full h-full flex items-center text-center justify-center'>
							<h1 className='text-white text-4xl font-bold z-20'>FELLOWSHIP</h1>
						</div>
					</div>
					<div className='relative rounded-xl h-96 w-96 shadow-lg shadow-[#0fc546]'>
						<div className='absolute rounded-xl left-0 top-0 z-10 w-full h-full bg-[#0fc546e3] bg-blend-overlay'></div>
						<div className='relative rounded-xl bg-hero w-full h-full flex items-center text-center justify-center'>
							<h1 className='text-white text-4xl font-bold z-20'>PRAYER</h1>
						</div>
					</div>
				</div>
				<div className='self-center grid justify-between justify-items-center grid-cols-1 md:grid-cols-2 lg:grid-cols-3 mx-auto max-w-full my-6 h-full'>
					{blogPosts.map((post) => {
						return (
							<Link key={post.title} href='/blog'>
								<div className='py-4'>
									<BlogCard post={post} />
								</div>
							</Link>
						);
					})}
				</div>
			</div>
		</div>
	);
}
